"use client";
import {FormEvent, useCallback, useEffect, useState} from "react";
import {api} from "../../lib/api";

const UNITS=["buc","ml","m2","m3","kg","tona","ora","set","sac","palet"];
type Kind="materials"|"labor"|"equipment";
const config={materials:{title:"Materiale generice",endpoint:"materials"},labor:{title:"Catalog manoperă",endpoint:"labor"},equipment:{title:"Catalog utilaje",endpoint:"equipment"}};

export default function CatalogClient({kind}:{kind:Kind}) {
  const meta=config[kind], priced=kind!=="materials";
  const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[showForm,setShowForm]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setRows(await api(`/api/catalog/${meta.endpoint}`));}catch(e){setError(e instanceof Error?e.message:"Eroare la încărcare.");}finally{setLoading(false);}},[meta.endpoint]);
  useEffect(()=>{load();},[load]);
  async function save(payload:any){setError("");try{await api(`/api/catalog/${meta.endpoint}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(payload)});setEditing(null);setShowForm(false);await load();}catch(e){setError(e instanceof Error?e.message:"Eroare la salvare.");}}
  return <main><div className="breadcrumbs"><a href="/">Proiecte</a><span>/</span><a href="/catalog/materiale">Cataloage</a><span>/</span><strong>{meta.title}</strong></div><header><div><h1>{meta.title}</h1><div className="muted">Resurse master reutilizabile în rețete și devize.</div></div><button className="primary" onClick={()=>{setEditing(null);setShowForm(true);}}>Adaugă</button></header><CatalogNav/>{error&&<div className="card error">{error}</div>}{(showForm||editing)&&<ResourceForm kind={kind} initial={editing} onCancel={()=>{setEditing(null);setShowForm(false);}} onSave={save}/>} {loading?<div className="card">Se încarcă...</div>:rows.length===0?<div className="empty">Catalogul este gol.</div>:<div className="card table-wrap"><table><thead><tr><th>Cod</th><th>Denumire</th><th>Unitate</th>{priced&&<><th>Net</th><th>TVA</th><th>Brut</th></>}<th>Stare</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.code}</td><td><strong>{row.name}</strong>{kind==="materials"&&<div className="muted">{row.category}</div>}</td><td>{row.base_unit||row.unit}</td>{priced&&<><td>{Number(row.rate_net).toLocaleString("ro-RO")} RON</td><td>{Number(row.vat_rate)}%</td><td>{Number(row.rate_gross).toLocaleString("ro-RO")} RON</td></>}<td>{row.active?"Activă":"Inactivă"}</td><td><button className="secondary" onClick={()=>{setEditing(row);setShowForm(false);}}>Editează</button>{kind==="materials"&&<> <a href={`/catalog/materiale/${row.id}/produse`}>Produse furnizori</a></>}</td></tr>)}</tbody></table></div>}</main>;
}

export function CatalogNav(){return <nav className="catalog-nav"><a href="/catalog/materiale">Materiale</a><a href="/catalog/manopera">Manoperă</a><a href="/catalog/utilaje">Utilaje</a><a href="/catalog/lucrari">Lucrări și rețete</a><a href="/suppliers">Furnizori</a></nav>}

function ResourceForm({kind,initial,onSave,onCancel}:{kind:Kind;initial:any;onSave:(p:any)=>void;onCancel:()=>void}){
 const material=kind==="materials"; const [code,setCode]=useState(initial?.code||""),[name,setName]=useState(initial?.name||""),[unit,setUnit]=useState(initial?.base_unit||initial?.unit||"buc"),[category,setCategory]=useState(initial?.category||"General"),[description,setDescription]=useState(initial?.description||""),[attributes,setAttributes]=useState(JSON.stringify(initial?.attributes||{},null,2)),[net,setNet]=useState(initial?.rate_net||"0"),[vat,setVat]=useState(initial?.vat_rate||"21"),[active,setActive]=useState(initial?.active??true),[validation,setValidation]=useState("");
 function submit(e:FormEvent){e.preventDefault();try{const common={code:code.trim(),name:name.trim(),active};onSave(material?{...common,category:category.trim(),base_unit:unit,description:description.trim()||null,attributes:JSON.parse(attributes||"{}")}:{...common,unit,rate_net:net,vat_rate:vat});}catch{setValidation("Atributele trebuie să fie JSON valid.");}}
 return <div className="card"><h2>{initial?"Editează resursa":"Resursă nouă"}</h2>{validation&&<div className="error">{validation}</div>}<form className="form-grid" onSubmit={submit}><div><label>Cod</label><input required maxLength={80} value={code} onChange={e=>setCode(e.target.value)}/></div><div><label>Denumire</label><input required maxLength={255} value={name} onChange={e=>setName(e.target.value)}/></div><div><label>Unitate</label><select value={unit} onChange={e=>setUnit(e.target.value)}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></div>{material?<><div><label>Categorie</label><input required value={category} onChange={e=>setCategory(e.target.value)}/></div><div className="wide"><label>Descriere</label><textarea value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="wide"><label>Atribute JSON</label><textarea value={attributes} onChange={e=>setAttributes(e.target.value)}/></div></>:<><div><label>Tarif net (RON)</label><input type="number" min="0" step="0.0001" required value={net} onChange={e=>setNet(e.target.value)}/></div><div><label>TVA (%)</label><input type="number" min="0" max="100" step="0.001" required value={vat} onChange={e=>setVat(e.target.value)}/></div></>}<label className="wide"><input style={{width:"auto"}} type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Resursă activă</label><div className="wide toolbar"><button className="primary">Salvează</button><button className="secondary" type="button" onClick={onCancel}>Renunță</button></div></form></div>
}
