"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {api} from "../../../../lib/api";
const UNITS=["buc","ml","m2","m3","kg","tona","ora","set","sac","palet"];
const TYPES=["MATERIAL","LABOR","EQUIPMENT","OTHER"];
const LABELS:Record<string,string>={MATERIAL:"Materiale",LABOR:"Manoperă",EQUIPMENT:"Utilaje",OTHER:"Alte costuri"};
type Line={id:number;source:string;resource_type:string;resource_id:number|null;description:string;unit:string;quantity:string;waste_percent:string;unit_price_net:string;vat_rate:string;vat_amount:string;unit_price_gross:string;subtotal_net:string;subtotal_gross:string};
type Item={id:number;code:string;description:string;unit:string;quantity:string;waste_percent:string;notes:string|null;work_item_id:number|null;calculation_type:string;calculation_inputs:Record<string,unknown>;sort_order:number;lines:Line[]};
type Section={id:number;code:string;name:string;items:Item[]}; type Level={id:number;name:string;sections:Section[]}; type Building={id:number;name:string;levels:Level[]};
function linesOf(value:any):Line[]{if(Array.isArray(value))return value.flatMap(linesOf);if(value?.lines)return value.lines;return value?Object.values(value).flatMap(linesOf):[]}
function totals(lines:Line[]){return lines.reduce((t,l)=>{t.net+=Number(l.subtotal_net);t.gross+=Number(l.subtotal_gross);t.by[l.resource_type]=(t.by[l.resource_type]||0)+Number(l.subtotal_gross);return t},{net:0,gross:0,by:{} as Record<string,number>})}
function ron(v:number){return v.toLocaleString("ro-RO",{minimumFractionDigits:2,maximumFractionDigits:2})+" RON"}
function Totals({value,label,full=false}:{value:any;label:string;full?:boolean}){const t=totals(linesOf(value));return <div className="subtotal"><strong>{label}</strong>{full&&TYPES.map(k=><span key={k}> • {LABELS[k]}: {ron(t.by[k]||0)}</span>)}<span> • Net: {ron(t.net)}</span><span> • TVA: {ron(t.gross-t.net)}</span><strong> • Total cu TVA: {ron(t.gross)}</strong>{full&&<span> • Transport: {ron(0)}</span>}</div>}

export default function EstimatePage(){const{id}=useParams<{id:string}>();const projectId=Number(id);const[project,setProject]=useState<any>(null),[buildings,setBuildings]=useState<Building[]>([]),[works,setWorks]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");try{
  const[p,w,bs]=await Promise.all([api(`/api/projects/${projectId}`),api("/api/catalog/work-items"),api(`/api/projects/${projectId}/buildings`)]);
  const full=await Promise.all(bs.map(async(b:any)=>{
   const rawLevels=await api(`/api/buildings/${b.id}/levels`);
   const levels=await Promise.all(rawLevels.map(async(l:any)=>{
    const rawSections=await api(`/api/levels/${l.id}/sections`);
    const sections=await Promise.all(rawSections.map(async(s:any)=>{
     const rawItems=await api(`/api/sections/${s.id}/items`);
     const items=await Promise.all(rawItems.map(async(i:any)=>({...i,lines:await api(`/api/estimate-items/${i.id}/resources`)})));
     return {...s,items};
    }));
    return {...l,sections};
   }));
   return {...b,levels};
  }));
  setProject(p);setWorks(w);setBuildings(full);
 }catch(e){setError(e instanceof Error?e.message:"Eroare la încărcarea devizului.");}finally{setLoading(false);}},[projectId]);useEffect(()=>{load();},[load]);
 if(loading)return <main><div className="card">Se calculează devizul...</div></main>;return <main><div className="breadcrumbs"><a href="/">Proiecte</a><span>/</span><a href={`/projects/${projectId}`}>{project?.name}</a><span>/</span><strong>Deviz valoric</strong></div><header><div><h1>Deviz — {project?.name}</h1><div className="muted">Cantități, rețete, resurse și costuri în RON cu TVA.</div></div><button className="secondary" onClick={load}>Recalculează</button></header>{error&&<div className="card error">{error}</div>}<Totals value={buildings} label="TOTAL PROIECT" full/>{buildings.length===0?<div className="empty">Proiectul nu are structură BOQ.</div>:buildings.map(b=><div className="hierarchy" key={b.id}><h2>{b.name}</h2><Totals value={b} label="Subtotal corp"/>{b.levels.map(l=><div className="hierarchy level" key={l.id}><h3>{l.name}</h3><Totals value={l} label="Subtotal nivel"/>{l.sections.map(s=><div className="hierarchy section" key={s.id}><h3>{s.code} — {s.name}</h3><Totals value={s} label="Subtotal capitol"/>{s.items.map(item=><ItemEstimate key={item.id} item={item} works={works} projectId={projectId} reload={load} setError={setError}/>)}</div>)}</div>)}</div>)}</main>}

function ItemEstimate({item,works,projectId,reload,setError}:{item:Item;works:any[];projectId:number;reload:()=>void;setError:(v:string)=>void}){const[workId,setWorkId]=useState(String(item.work_item_id||"")),[manual,setManual]=useState(false);async function run(action:()=>Promise<any>){try{await action();await reload();}catch(e){setError(e instanceof Error?e.message:"Operația a eșuat.");}}
 async function associate(){const payload={code:item.code,description:item.description,notes:item.notes,unit:item.unit,quantity:item.quantity,waste_percent:item.waste_percent,work_item_id:Number(workId),calculation_type:item.calculation_type,calculation_inputs:item.calculation_inputs,sort_order:item.sort_order};await run(()=>api(`/api/estimate-items/${item.id}`,{method:"PUT",body:JSON.stringify(payload)}));}
 return <div className="card"><div className="toolbar push"><div><strong>{item.code} — {item.description}</strong><div className="muted">{item.quantity} {item.unit}</div></div><div className="toolbar"><select value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">Lucrare neasociată</option>{works.map(w=><option value={w.id} key={w.id}>{w.code} — {w.name}</option>)}</select><button className="secondary" disabled={!workId} onClick={associate}>Asociază</button><button className="primary" disabled={!item.work_item_id} onClick={()=>run(()=>api(`/api/estimate-items/${item.id}/resources/generate`,{method:"POST"}))}>Generează din rețetă</button><button className="secondary" onClick={()=>setManual(true)}>Linie manuală</button></div></div><Totals value={item} label="Total articol"/>{manual&&<ManualForm itemId={item.id} onDone={()=>{setManual(false);reload();}}/>}{item.lines.length===0?<div className="empty">Articolul nu are resurse calculate.</div>:<div className="table-wrap"><table><thead><tr><th>Tip</th><th>Resursă</th><th>Cantitate</th><th>Preț net</th><th>TVA</th><th>Preț brut</th><th>Subtotal net</th><th>Subtotal brut</th><th></th></tr></thead><tbody>{item.lines.map(l=><tr key={l.id}><td>{LABELS[l.resource_type]}</td><td>{l.description}<div className="muted">{l.source}</div></td><td>{l.quantity} {l.unit}</td><td className="money">{ron(Number(l.unit_price_net))}</td><td>{l.vat_rate}%<div className="muted">{ron(Number(l.vat_amount))}</div></td><td className="money">{ron(Number(l.unit_price_gross))}</td><td className="money">{ron(Number(l.subtotal_net))}</td><td className="money"><strong>{ron(Number(l.subtotal_gross))}</strong></td><td>{l.resource_id&&<button className="secondary" onClick={()=>{const net=prompt("Preț net proiect (RON)",l.unit_price_net),vat=prompt("TVA proiect (%)",l.vat_rate);if(net!==null&&vat!==null)run(async()=>{await api(`/api/projects/${projectId}/resource-prices`,{method:"PUT",body:JSON.stringify({resource_type:l.resource_type,resource_id:l.resource_id,unit_price_net:net,vat_rate:vat})});if(item.work_item_id)await api(`/api/estimate-items/${item.id}/resources/generate`,{method:"POST"});});}}>Preț proiect</button>}</td></tr>)}</tbody></table></div>}</div>}

function ManualForm({itemId,onDone}:{itemId:number;onDone:()=>void}){const[type,setType]=useState("OTHER"),[description,setDescription]=useState(""),[unit,setUnit]=useState("buc"),[quantity,setQuantity]=useState("1"),[waste,setWaste]=useState("0"),[net,setNet]=useState("0"),[vat,setVat]=useState("21");async function submit(e:FormEvent){e.preventDefault();await api(`/api/estimate-items/${itemId}/resources`,{method:"POST",body:JSON.stringify({resource_type:type,resource_id:null,description,unit,quantity,waste_percent:waste,unit_price_net:net,vat_rate:vat,notes:null})});onDone();}return <form className="form-grid" onSubmit={submit}><div><label>Tip</label><select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(t=><option key={t} value={t}>{LABELS[t]}</option>)}</select></div><div><label>Descriere</label><input required value={description} onChange={e=>setDescription(e.target.value)}/></div><div><label>Unitate</label><select value={unit} onChange={e=>setUnit(e.target.value)}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></div><div><label>Cantitate</label><input type="number" min="0.000001" step="0.000001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></div><div><label>Pierderi (%)</label><input type="number" min="0" max="100" value={waste} onChange={e=>setWaste(e.target.value)}/></div><div><label>Preț net</label><input type="number" min="0" step="0.0001" value={net} onChange={e=>setNet(e.target.value)}/></div><div><label>TVA (%)</label><input type="number" min="0" max="100" value={vat} onChange={e=>setVat(e.target.value)}/></div><button className="primary">Adaugă linia</button></form>}
