"use client";
import {useParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../../../lib/api";

type Def={label:string,type:string,fields:[string,string,string][],results:Record<string,string>};
const D:Def[]=[
 {label:"Încăperi",type:"ROOM",fields:[["length_m","Lungime","5"],["width_m","Lățime","4"],["height_m","Înălțime","2.8"]],results:{floor_area_m2:"Pardoseală",ceiling_area_m2:"Tavan",gross_wall_area_m2:"Pereți brut",opening_area_m2:"Goluri",net_wall_area_m2:"Pereți net",perimeter_m:"Perimetru",skirting_length_m:"Plintă"}},
 {label:"Pereți",type:"WALL",fields:[["length_m","Lungime","5"],["height_m","Înălțime","2.8"],["thickness_m","Grosime","0.25"]],results:{gross_area_m2:"Suprafață brută",net_area_m2:"Suprafață netă",volume_m3:"Volum zidărie"}},
 {label:"Fundații",type:"FOUNDATION_STRIP",fields:[["length_m","Lungime","10"],["excavation_width_m","Lățime săpătură","0.8"],["excavation_depth_m","Adâncime săpătură","1.2"],["concrete_width_m","Lățime beton","0.5"],["concrete_height_m","Înălțime beton","0.8"],["blinding_thickness_m","Beton egalizare","0.1"]],results:{excavation_m3:"Săpătură",concrete_m3:"Beton",blinding_concrete_m3:"Beton egalizare",side_formwork_m2:"Cofraj lateral"}},
 {label:"Plăci",type:"SLAB",fields:[["length_m","Lungime","10"],["width_m","Lățime","8"],["thickness_m","Grosime","0.15"]],results:{area_m2:"Suprafață",concrete_volume_m3:"Volum beton",bottom_formwork_m2:"Cofraj inferior",perimeter_m:"Perimetru"}},
 {label:"Grinzi",type:"BEAM",fields:[["length_m","Lungime","5"],["width_m","Lățime","0.3"],["height_m","Înălțime","0.5"],["quantity","Număr","1"]],results:{concrete_volume_m3:"Volum beton",formwork_area_m2:"Cofraj"}},
 {label:"Stâlpi",type:"COLUMN",fields:[["width_m","Lățime","0.4"],["depth_m","Adâncime","0.4"],["height_m","Înălțime","3"],["quantity","Număr","1"]],results:{concrete_volume_m3:"Volum beton",formwork_area_m2:"Cofraj"}},
 {label:"Armături",type:"REBAR",fields:[["group_type","Tip grup","LONGITUDINAL"],["diameter_mm","Diametru mm","12"],["bar_length_m","Lungime bară","6"],["quantity","Număr bare","10"],["lap_allowance_m","Suprapunere","0.6"],["hook_allowance_m","Ciocuri","0.2"]],results:{total_length_m:"Lungime totală",total_weight_kg:"Greutate oțel"}},
 {label:"Plasă sudată",type:"WELDED_MESH",fields:[["coverage_length_m","Lungime acoperită","8"],["coverage_width_m","Lățime acoperită","5"],["sheet_length_m","Lungime foaie","5"],["sheet_width_m","Lățime foaie","2"],["overlap_x_m","Suprapunere X","0.5"],["overlap_y_m","Suprapunere Y","0.2"],["layers","Straturi","1"],["weight_kg_per_sheet","kg / foaie","20"]],results:{total_sheets:"Număr foi",total_weight_kg:"Greutate totală"}},
 {label:"Acoperiș",type:"ROOF_GABLE",fields:[["building_length_m","Lungime clădire","10"],["building_width_m","Lățime clădire","8"],["pitch_degrees","Pantă grade","30"],["eave_overhang_m","Streașină","0.5"],["gable_overhang_m","Fronton","0.3"]],results:{projected_area_m2:"Suprafață proiectată",slope_length_m:"Lungime pantă",total_roof_surface_m2:"Suprafață acoperiș",ridge_length_m:"Coamă",eave_length_m:"Streașină totală"}}
];
const stirrups:Def={label:"Etrieri",type:"STIRRUPS",fields:[["beam_length_m","Lungime grindă","5"],["beam_width_m","Lățime grindă","0.3"],["beam_height_m","Înălțime grindă","0.5"],["concrete_cover_mm","Acoperire beton mm","25"],["stirrup_diameter_mm","Diametru mm","8"],["spacing_mm","Pas mm","200"],["hook_length_m","Cioc","0.1"]],results:{number_of_stirrups:"Număr etrieri",cutting_length_m:"Lungime debitare",total_weight_kg:"Greutate oțel"}};
const unitLabel:Record<string,string>={m2:"m²",m3:"m³",ml:"m",kg:"kg",buc:"buc"};
export default function GeometryPage(){
 const projectId=useParams<{id:string}>().id; const [tab,setTab]=useState(0),[steel,setSteel]=useState("REBAR"); const def=useMemo(()=>D[tab].type==="REBAR"&&steel==="STIRRUPS"?stirrups:D[tab],[tab,steel]);
 const [values,setValues]=useState<Record<string,string>>({}),[openings,setOpenings]=useState<any[]>([]),[selected,setSelected]=useState(""),[waste,setWaste]=useState("0"),[name,setName]=useState("Calcul geometric"),[itemId,setItemId]=useState(""),[parentId,setParentId]=useState(""),[preview,setPreview]=useState<any>(),[rows,setRows]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[sections,setSections]=useState<any[]>([]),[editing,setEditing]=useState<number|null>(null),[error,setError]=useState("");
 useEffect(()=>{setValues(Object.fromEntries(def.fields.map(x=>[x[0],x[2]])));setSelected(Object.keys(def.results)[0]);setOpenings([]);setPreview(undefined);setEditing(null)},[def]);
 async function load(){try{setRows(await api(`/api/projects/${projectId}/geometry`));const bs=await api(`/api/projects/${projectId}/buildings`),list:any[]=[],sectionList:any[]=[];for(const b of bs)for(const l of await api(`/api/buildings/${b.id}/levels`))for(const s of await api(`/api/levels/${l.id}/sections`)){sectionList.push({...s,label:`${b.name} / ${l.name} / ${s.code} ${s.name}`});for(const i of await api(`/api/sections/${s.id}/items`))list.push({...i,label:`${b.name} / ${l.name} / ${s.code} / ${i.code}`})}setItems(list);setSections(sectionList)}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[projectId]);
 const payload=useMemo(()=>({estimate_item_id:itemId?Number(itemId):null,parent_calculation_id:parentId?Number(parentId):null,geometry_type:def.type,name,input_data:{...values,...(["ROOM","WALL"].includes(def.type)?{openings}:{}),...(def.type==="BEAM"?{exposed_faces:["bottom","side_left","side_right","ends"]}:{}),...(["REBAR","STIRRUPS","WELDED_MESH"].includes(def.type)?{waste_percent:waste}:{})},selected_result:selected,waste_percent:waste}),[def,itemId,parentId,name,openings,selected,values,waste]);
 useEffect(()=>{if(!selected)return;const t=setTimeout(()=>api(`/api/projects/${projectId}/geometry/calculate`,{method:"POST",body:JSON.stringify(payload)}).then(x=>{setPreview(x);setError("")}).catch((e:any)=>setError(e.message)),250);return()=>clearTimeout(t)},[payload,projectId,selected]);
 async function save(){try{await api(editing?`/api/geometry/${editing}`:`/api/projects/${projectId}/geometry`,{method:editing?"PUT":"POST",body:JSON.stringify(payload)});setEditing(null);await load()}catch(e:any){setError(e.message)}}
 function edit(x:any){const ix=D.findIndex(d=>d.type===x.geometry_type||(x.geometry_type==="STIRRUPS"&&d.type==="REBAR"));setTab(ix);if(x.geometry_type==="STIRRUPS")setSteel("STIRRUPS");setTimeout(()=>{setEditing(x.id);setName(x.name);setValues(x.input_data);setOpenings(x.input_data.openings||[]);setSelected(x.selected_result);setWaste(String(x.waste_percent));setItemId(x.estimate_item_id?String(x.estimate_item_id):"");setParentId(x.parent_calculation_id?String(x.parent_calculation_id):"")},0)}
 function addOpening(type:string){setOpenings([...openings,{type,width_m:type==="DOOR"?"0.9":"1.2",height_m:type==="DOOR"?"2.1":"1.4",quantity:"1"}])}
 async function createItem(x:any){if(!sections.length){setError("Creează mai întâi un capitol de deviz.");return}const choices=sections.map((s,i)=>`${i+1}. ${s.label}`).join("\n"),choice=Number(prompt(`Alege capitolul:\n${choices}`,"1"))-1,code=prompt("Cod articol nou:","GEO-01"),description=prompt("Denumire articol nou:",x.name);if(!sections[choice]||!code||!description)return;try{await api(`/api/geometry/${x.id}/create-item`,{method:"POST",body:JSON.stringify({section_id:sections[choice].id,result_key:x.selected_result,code,description,waste_percent:x.waste_percent})});await load()}catch(e:any){setError(e.message)}}
 return <main><div className="breadcrumbs"><a href="/">Proiecte</a><span>/</span><a href={`/projects/${projectId}`}>Proiect</a><span>/</span><strong>Geometrie</strong></div><header><div><h1>Calcul geometric</h1><div className="muted">Dimensiuni → cantități BOQ → resurse de deviz</div></div><a href={`/projects/${projectId}/estimate`}>Deviz valoric</a></header>
 <div className="tabs">{D.map((x,i)=><button key={x.type} className={i===tab?"primary":"secondary"} onClick={()=>setTab(i)}>{x.label}</button>)}</div>{D[tab].type==="REBAR"&&<div className="toolbar"><button className={steel==="REBAR"?"primary":"secondary"} onClick={()=>setSteel("REBAR")}>Bare</button><button className={steel==="STIRRUPS"?"primary":"secondary"} onClick={()=>setSteel("STIRRUPS")}>Etrieri</button></div>}{error&&<div className="card error">{error}</div>}
 <section className="card"><h2>{editing?"Editează":"Adaugă"} {def.label.toLowerCase()}</h2><div className="form-grid"><label>Denumire<input value={name} onChange={e=>setName(e.target.value)}/></label>{def.fields.map(x=><label key={x[0]}>{x[1]}{x[0]==="group_type"?<select value={values[x[0]]} onChange={e=>setValues({...values,[x[0]]:e.target.value})}><option value="LONGITUDINAL">Longitudinală</option><option value="DISTRIBUTION">Distribuție</option><option value="ADDITIONAL">Suplimentară</option></select>:<input type="number" min="0" step="0.001" value={values[x[0]]??""} onChange={e=>setValues({...values,[x[0]]:e.target.value})}/>}</label>)}<label>Pierderi %<input type="number" min="0" max="100" value={waste} onChange={e=>setWaste(e.target.value)}/></label><label>Rezultat conectat<select value={selected} onChange={e=>setSelected(e.target.value)}>{Object.entries(def.results).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Articol existent (opțional)<select value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Fără legătură</option>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{["REBAR","STIRRUPS"].includes(def.type)&&<label>Element structural<select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Fără element părinte</option>{rows.filter(x=>["FOUNDATION_STRIP","SLAB","BEAM","COLUMN"].includes(x.geometry_type)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div>
 {(["ROOM","WALL"].includes(def.type))&&<><div className="toolbar"><button className="secondary" onClick={()=>addOpening("DOOR")}>Adaugă ușă</button><button className="secondary" onClick={()=>addOpening("WINDOW")}>Adaugă fereastră</button></div>{openings.map((o,i)=><div className="inline-form" key={i}><strong>{o.type==="DOOR"?"Ușă":"Fereastră"}</strong>{["width_m","height_m","quantity"].map(k=><input key={k} type="number" value={o[k]} onChange={e=>setOpenings(openings.map((a,j)=>j===i?{...a,[k]:e.target.value}:a))}/>)}</div>)}</>}
 {preview&&<div className="results-grid">{Object.entries(def.results).map(([k,label])=><div key={k}><span>{label}</span><strong>{Number(preview.results[k]).toLocaleString("ro-RO",{maximumFractionDigits:3})}</strong></div>)}{[["Cantitate geometrică",preview.geometric_quantity],["Pierderi",preview.waste_quantity],["Cantitate deviz",preview.estimate_quantity]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{Number(x[1]).toFixed(3)} {unitLabel[preview.calculated_unit]||preview.calculated_unit}</strong></div>)}</div>}<details><summary>Vezi calculul</summary><code>{def.fields.map(x=>values[x[0]]).join(" × ")} = {preview?Number(preview.geometric_quantity).toFixed(3):"—"}</code></details><div className="toolbar"><button className="primary" onClick={save}>Salvează calculul</button>{editing&&<button className="secondary" onClick={()=>setEditing(null)}>Renunță</button>}</div></section>
 <h2>Calcule salvate</h2>{rows.length===0?<div className="empty">Nu există calcule geometrice.</div>:<div className="card table-wrap"><table><thead><tr><th>Denumire</th><th>Tip</th><th>Rezultat</th><th>Cantitate deviz</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.geometry_type}</td><td>{x.selected_result}</td><td>{Number(x.calculated_quantity).toFixed(3)} {unitLabel[x.calculated_unit]||x.calculated_unit}</td><td><button className="secondary" onClick={()=>edit(x)}>Editează</button> <button className="secondary" onClick={()=>createItem(x)}>Creează articol</button> <button className="danger" onClick={async()=>{if(confirm(`Ștergi calculul „${x.name}”?`)){await api(`/api/geometry/${x.id}`,{method:"DELETE"});load()}}}>Șterge</button></td></tr>)}</tbody></table></div>}</main>
}
