"""procurement landed cost

Revision ID: 0007_procurement_landed_cost
Revises: 0006_supplier_integrations
"""
from alembic import op
import sqlalchemy as sa
revision="0007_procurement_landed_cost";down_revision="0006_supplier_integrations";branch_labels=None;depends_on=None

def upgrade():
    for c in [sa.Column("delivery_locality",sa.String(120),nullable=False,server_default="Ceahlău"),sa.Column("delivery_county",sa.String(120),nullable=False,server_default="Neamț"),sa.Column("delivery_country",sa.String(80),nullable=False,server_default="România"),sa.Column("latitude",sa.Numeric(10,7)),sa.Column("longitude",sa.Numeric(10,7))]:op.add_column("projects",c)
    op.execute("UPDATE projects SET delivery_locality=locality,delivery_county=county")
    for c in [sa.Column("minimum_order_quantity",sa.Numeric(18,6)),sa.Column("minimum_package_count",sa.Integer(),nullable=False,server_default="1"),sa.Column("whole_pallet_only",sa.Boolean(),nullable=False,server_default=sa.false())]:op.add_column("supplier_products",c)
    with op.batch_alter_table("delivery_quotes") as b:b.alter_column("cost_gross",new_column_name="delivery_cost_gross")
    for c in [sa.Column("destination_address",sa.Text()),sa.Column("basket_subtotal_gross",sa.Numeric(18,2),nullable=False,server_default="0"),sa.Column("basket_weight_kg",sa.Numeric(18,3)),sa.Column("pallet_count",sa.Numeric(18,3)),sa.Column("currency",sa.String(3),nullable=False,server_default="RON"),sa.Column("valid_from",sa.DateTime(timezone=True),nullable=True),sa.Column("valid_until",sa.DateTime(timezone=True)),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true())]:op.add_column("delivery_quotes",c)
    op.execute("UPDATE delivery_quotes SET valid_from=checked_at")
    with op.batch_alter_table("delivery_quotes") as b:b.alter_column("valid_from",nullable=False)
    op.create_table("supplier_delivery_rules",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("supplier_id",sa.Integer(),sa.ForeignKey("suppliers.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("minimum_order_gross",sa.Numeric(18,2)),sa.Column("fixed_delivery_cost",sa.Numeric(18,2)),sa.Column("free_delivery_threshold",sa.Numeric(18,2)),sa.Column("cost_per_km",sa.Numeric(18,4)),sa.Column("cost_per_pallet",sa.Numeric(18,4)),sa.Column("cost_per_kg",sa.Numeric(18,4)),sa.Column("minimum_delivery_cost",sa.Numeric(18,2)),sa.Column("notes",sa.Text()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("procurement_plans",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("estimate_version_id",sa.Integer(),sa.ForeignKey("estimate_versions.id")),sa.Column("strategy",sa.String(40),nullable=False),sa.Column("preferred_supplier_id",sa.Integer(),sa.ForeignKey("suppliers.id")),sa.Column("status",sa.String(20),nullable=False),sa.Column("include_unknown_delivery",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("procurement_plan_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("procurement_plan_id",sa.Integer(),sa.ForeignKey("procurement_plans.id",ondelete="CASCADE"),nullable=False),sa.Column("estimate_resource_id",sa.Integer(),sa.ForeignKey("estimate_resource_lines.id"),nullable=False),sa.Column("material_id",sa.Integer(),sa.ForeignKey("materials.id"),nullable=False),sa.Column("supplier_id",sa.Integer(),sa.ForeignKey("suppliers.id"),nullable=False),sa.Column("supplier_product_id",sa.Integer(),sa.ForeignKey("supplier_products.id"),nullable=False),sa.Column("required_quantity",sa.Numeric(18,6),nullable=False),sa.Column("required_unit",sa.String(20),nullable=False),sa.Column("package_quantity",sa.Numeric(18,6),nullable=False),sa.Column("package_unit",sa.String(20),nullable=False),sa.Column("packages_to_buy",sa.Integer(),nullable=False),sa.Column("purchased_quantity",sa.Numeric(18,6),nullable=False),sa.Column("unused_quantity",sa.Numeric(18,6),nullable=False),sa.Column("unit_package_price_gross",sa.Numeric(18,4),nullable=False),sa.Column("product_subtotal_gross",sa.Numeric(18,2),nullable=False),sa.Column("price_checked_at",sa.DateTime(timezone=True),nullable=False),sa.Column("stock_status",sa.String(40),nullable=False),sa.Column("manual_override",sa.Boolean(),nullable=False),sa.Column("supplier_name",sa.String(160),nullable=False),sa.Column("supplier_sku",sa.String(120),nullable=False),sa.Column("product_name",sa.String(500),nullable=False),sa.Column("product_url",sa.Text(),nullable=False),sa.Column("notes",sa.Text()))
    op.create_table("procurement_plan_supplier_totals",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("procurement_plan_id",sa.Integer(),sa.ForeignKey("procurement_plans.id",ondelete="CASCADE"),nullable=False),sa.Column("supplier_id",sa.Integer(),sa.ForeignKey("suppliers.id"),nullable=False),sa.Column("product_count",sa.Integer(),nullable=False),sa.Column("subtotal_gross",sa.Numeric(18,2),nullable=False),sa.Column("delivery_cost_gross",sa.Numeric(18,2)),sa.Column("delivery_source",sa.String(20),nullable=False),sa.Column("landed_total_gross",sa.Numeric(18,2)))

def downgrade():
    op.drop_table("procurement_plan_supplier_totals");op.drop_table("procurement_plan_items");op.drop_table("procurement_plans");op.drop_table("supplier_delivery_rules")
    for n in ["active","valid_until","valid_from","currency","pallet_count","basket_weight_kg","basket_subtotal_gross","destination_address"]:op.drop_column("delivery_quotes",n)
    with op.batch_alter_table("delivery_quotes") as b:b.alter_column("delivery_cost_gross",new_column_name="cost_gross")
    for n in ["whole_pallet_only","minimum_package_count","minimum_order_quantity"]:op.drop_column("supplier_products",n)
    for n in ["longitude","latitude","delivery_country","delivery_county","delivery_locality"]:op.drop_column("projects",n)
