"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {api} from "../../lib/api";
const money=(v:any)=>Number(v||0).toLocaleString("ro-RO",{minimumFractionDigits:2,maximumFractionDigits:2});
const statusLabel:any={HEALTHY:"✓ Sănătos",DEGRADED:"⚠ Degradat",FAILED:"✕ Eșuat",UNKNOWN:"? Necunoscut"};
export default function SupplierClient({code}:{code?:string}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[supplier,setSupplier]=useState("DEDEMAN"),[url,setUrl]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await api(code?`/api/suppliers/${code}`:"/api/suppliers"));}catch(e){setError(e instanceof Error?e.message:"Eroare la încărcare.");}finally{setLoading(false);}},[code]);useEffect(()=>{load()},[load]);
 async function importUrl(e:FormEvent){e.preventDefault();try{await api("/api/suppliers/import-url",{method:"POST",body:JSON.stringify({supplier,url})});setUrl("");await load();}catch(e){setError(e instanceof Error?e.message:"Importul a eșuat.");}}
 async function refresh(product?:any){try{await api("/api/suppliers/refresh",{method:"POST",body:JSON.stringify(product?{supplier_product_id:product.id}:{supplier_id:data.id,job_type:"SUPPLIER"})});alert("Actualizarea a fost programată.");}catch(e){setError(e instanceof Error?e.message:"Programarea a eșuat.");}}
 if(loading)return <main><div className="card">Se încarcă furnizorii...</div></main>;const suppliers=code?[data]:data||[];
 return <main><div className="breadcrumbs"><a href="/">Proiecte</a><span>/</span><strong>Furnizori</strong>{code&&<><span>/</span><strong>{data?.name}</strong></>}</div><header><div><h1>{code?data?.name:"Furnizori"}</h1><div className="muted">Produse publice asociate materialelor generice. Stocul neconfirmat rămâne necunoscut.</div></div>{code&&<button className="primary" onClick={()=>refresh()}>Actualizează prețurile</button>}</header>{error&&<div className="card error">{error}</div>}
 {!code&&<div className="card"><h2>Importă produs</h2><form className="form-grid" onSubmit={importUrl}><div><label>Furnizor</label><select value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="DEDEMAN">Dedeman</option><option value="MATHAUS">MatHaus</option><option value="LEROY_MERLIN">Leroy Merlin</option><option value="HORNBACH">Hornbach</option></select></div><div className="wide"><label>URL produs public</label><input type="url" required placeholder="https://..." value={url} onChange={e=>setUrl(e.target.value)}/></div><button className="primary">Importă</button></form></div>}
 <div className="cards">{suppliers.map((s:any)=><div className="card" key={s.id}><h2>{s.name}</h2><p><strong>{statusLabel[s.status]||statusLabel.UNKNOWN}</strong></p><p className="muted">Ultima verificare reușită: {s.last_success?new Date(s.last_success).toLocaleString("ro-RO"):"Nicio verificare"}</p><p>{s.products_tracked} produse · {s.price_observations} observații · {s.manual_imports} importuri manuale</p><p>{s.failures} eșecuri · {s.parse_failures} erori de parsare</p>{s.last_error&&<p className="error">{s.last_error}</p>}{!code&&<a className="button secondary" href={`/suppliers/${s.code.toLowerCase()}`}>Deschide furnizorul</a>}</div>)}</div>
 {code&&(data.products?.length?<div className="card table-wrap"><table><thead><tr><th>Produs</th><th>SKU</th><th>Ambalaj</th><th>Preț curent</th><th>Preț anterior</th><th>Diferență</th><th>Preț normalizat</th><th>Stoc</th><th>Ultima verificare</th><th></th></tr></thead><tbody>{data.products.map((p:any)=><tr key={p.id}><td><strong>{p.name}</strong><div className="muted">{p.brand||"Marcă nespecificată"}</div></td><td>{p.supplier_sku}</td><td>{p.package_quantity||"—"} {p.package_unit||""}</td><td>{p.price?`${money(p.price.gross)} lei`:"—"}</td><td>{p.price?.previous_gross?`${money(p.price.previous_gross)} lei`:"—"}</td><td>{p.price?.difference!=null?`${money(p.price.difference)} lei`:"—"}</td><td>{p.normalized_price_gross?`${money(p.normalized_price_gross)} lei/${p.normalized_unit}`:"—"}</td><td>{p.price?.stock_status||"UNKNOWN"}</td><td>{p.price?.checked_at?new Date(p.price.checked_at).toLocaleString("ro-RO"):"—"}</td><td><button className="secondary" onClick={()=>refresh(p)}>Actualizează</button> <a href={p.product_url} target="_blank" rel="noreferrer">Produs</a></td></tr>)}</tbody></table></div>:<div className="empty">Nu există produse importate pentru acest furnizor.</div>)}
 </main>;
}
