"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {api} from "../../../lib/api";
import {CatalogNav} from "../catalog-client";
const UNITS=["buc","ml","m2","m3","kg","tona","ora","set","sac","palet"];
const TYPES=[{v:"MATERIAL",l:"Material"},{v:"LABOR",l:"Manoperă"},{v:"EQUIPMENT",l:"Utilaj"},{v:"OTHER",l:"Alte costuri"}];

export default function Page(){
 const [works,setWorks]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[recipes,setRecipes]=useState<any[]>([]),[recipe,setRecipe]=useState<any|null>(null),[resources,setResources]=useState<Record<string,any[]>>({}),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [w,m,l,e,o]=await Promise.all([api("/api/catalog/work-items"),api("/api/catalog/materials"),api("/api/catalog/labor"),api("/api/catalog/equipment"),api("/api/catalog/other")]);setWorks(w);setResources({MATERIAL:m,LABOR:l,EQUIPMENT:e,OTHER:o});}catch(e){setError(e instanceof Error?e.message:"Eroare la încărcare.");}},[]);
 useEffect(()=>{load();},[load]);
 async function choose(work:any){setSelected(work);setRecipe(null);setRecipes(await api(`/api/work-items/${work.id}/recipes`));}
 async function reloadRecipes(){if(selected)setRecipes(await api(`/api/work-items/${selected.id}/recipes`));}
 return <main><div className="breadcrumbs"><a href="/">Proiecte</a><span>/</span><strong>Lucrări și rețete</strong></div><header><div><h1>Lucrări și rețete</h1><div className="muted">Rețete standard, override companie și override proiect.</div></div></header><CatalogNav/>{error&&<div className="card error">{error}</div>}<WorkForm onSaved={load}/><div className="grid"><div className="card"><h2>Lucrări</h2>{works.length===0?<div className="empty">Nu există lucrări.</div>:works.map(w=><button style={{display:"block",width:"100%",marginBottom:8}} className={selected?.id===w.id?"primary":"secondary"} key={w.id} onClick={()=>choose(w)}>{w.code} — {w.name}</button>)}</div><div>{selected?<><RecipeForm work={selected} onSaved={reloadRecipes}/><div className="card"><h2>Rețete pentru {selected.name}</h2>{recipes.length===0?<div className="empty">Nu există rețete.</div>:recipes.map(r=><button style={{display:"block",width:"100%",marginBottom:8}} className={recipe?.id===r.id?"primary":"secondary"} key={r.id} onClick={()=>setRecipe(r)}>{r.scope.replaceAll("_"," ")} • versiunea {r.version}{r.project_id?` • proiect ${r.project_id}`:""}</button>)}</div>{recipe&&<RecipeResourceForm recipe={recipe} resources={resources}/>}</>:<div className="empty">Selectează o lucrare pentru a administra rețetele.</div>}</div></div></main>
}

function WorkForm({onSaved}:{onSaved:()=>void}){const[code,setCode]=useState(""),[name,setName]=useState(""),[category,setCategory]=useState("General"),[unit,setUnit]=useState("buc");async function submit(e:FormEvent){e.preventDefault();await api("/api/catalog/work-items",{method:"POST",body:JSON.stringify({code,name,category,unit,description:null,active:true})});setCode("");setName("");onSaved();}return <div className="card"><h2>Lucrare nouă</h2><form className="form-grid" onSubmit={submit}><div><label>Cod</label><input required value={code} onChange={e=>setCode(e.target.value)}/></div><div><label>Denumire</label><input required value={name} onChange={e=>setName(e.target.value)}/></div><div><label>Categorie</label><input required value={category} onChange={e=>setCategory(e.target.value)}/></div><div><label>Unitate</label><select value={unit} onChange={e=>setUnit(e.target.value)}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></div><button className="primary">Adaugă lucrare</button></form></div>}

function RecipeForm({work,onSaved}:{work:any;onSaved:()=>void}){const[scope,setScope]=useState("STANDARD"),[version,setVersion]=useState("1"),[projectId,setProjectId]=useState("");async function submit(e:FormEvent){e.preventDefault();await api("/api/recipes",{method:"POST",body:JSON.stringify({work_item_id:work.id,scope,version:Number(version),project_id:scope==="PROJECT_OVERRIDE"?Number(projectId):null})});onSaved();}return <div className="card"><h2>Rețetă nouă</h2><form className="form-grid" onSubmit={submit}><div><label>Nivel moștenire</label><select value={scope} onChange={e=>setScope(e.target.value)}><option value="STANDARD">STANDARD</option><option value="COMPANY_OVERRIDE">OVERRIDE COMPANIE</option><option value="PROJECT_OVERRIDE">OVERRIDE PROIECT</option></select></div><div><label>Versiune</label><input type="number" min="1" required value={version} onChange={e=>setVersion(e.target.value)}/></div>{scope==="PROJECT_OVERRIDE"&&<div><label>ID proiect</label><input type="number" min="1" required value={projectId} onChange={e=>setProjectId(e.target.value)}/></div>}<button className="primary">Creează rețeta</button></form></div>}

function RecipeResourceForm({recipe,resources}:{recipe:any;resources:Record<string,any[]>}){const[type,setType]=useState("MATERIAL"),[resourceId,setResourceId]=useState(""),[quantity,setQuantity]=useState("1"),[waste,setWaste]=useState("0"),[unit,setUnit]=useState("buc"),[notes,setNotes]=useState(""),[lines,setLines]=useState<any[]>([]);const load=useCallback(async()=>setLines(await api(`/api/recipes/${recipe.id}/resources`)),[recipe.id]);useEffect(()=>{load();},[load]);useEffect(()=>setResourceId(""),[type]);async function submit(e:FormEvent){e.preventDefault();await api(`/api/recipes/${recipe.id}/resources`,{method:"POST",body:JSON.stringify({resource_type:type,resource_id:Number(resourceId),quantity_per_unit:quantity,waste_percent:waste,unit,notes:notes||null})});setNotes("");load();}return <div className="card"><h2>Resurse rețetă</h2><form className="form-grid" onSubmit={submit}><div><label>Tip</label><select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(t=><option value={t.v} key={t.v}>{t.l}</option>)}</select></div><div><label>Resursă</label><select required value={resourceId} onChange={e=>setResourceId(e.target.value)}><option value="">Selectează</option>{(resources[type]||[]).map(r=><option value={r.id} key={r.id}>{r.code} — {r.name}</option>)}</select></div><div><label>Cantitate / unitate lucrare</label><input type="number" min="0.000001" step="0.000001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></div><div><label>Pierderi (%)</label><input type="number" min="0" max="100" step="0.001" value={waste} onChange={e=>setWaste(e.target.value)}/></div><div><label>Unitate</label><select value={unit} onChange={e=>setUnit(e.target.value)}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></div><div><label>Note</label><input value={notes} onChange={e=>setNotes(e.target.value)}/></div><button className="primary">Adaugă resursa</button></form>{lines.length===0?<div className="empty">Rețeta nu are resurse.</div>:<table><tbody>{lines.map(l=><tr key={l.id}><td>{l.resource_type}</td><td>{l.description}</td><td>{l.quantity_per_unit} {l.unit}</td><td>{l.waste_percent}%</td></tr>)}</tbody></table>}</div>}
